### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by gemmaro** [puripuri2100/learn-satysfi#2]
I think that it would be nice to be able to view generated documentation on the web.
I'm not familiar with mdBook or GitHub Actions, but it seems to be easy to achieve using [existing GitHub Actions](https://github.com/marketplace/actions/mdbook-action).
I've forked and added the GitHub Actions settings to https://github.com/gemmaro/learn-satysfi. (And it can be viewed at https://gemmaro.github.io/learn-satysfi/.)

**Comment by puripuri2100** [comment]
We are able to view generated documentation on the web.
https://puripuri2100.github.io/learn-satysfi/

thanks!
